package com.seezoon.framework.modules.zhfw.entity;

import com.seezoon.framework.common.entity.BaseEntity;

import java.util.Date;

public class Froperaccnt extends BaseEntity<String> {

    private static final long serialVersionUID = 1L;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.FROAID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String froaid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.XGYHZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String xgyhzh1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.XGYHZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String xgyhzh2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZJLX
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String zjlx;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHDLMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhdlmm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WT2WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wt2wt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.FROANO
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String froano;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.AREALIMIT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String arealimit;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.KCZYHZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String kczyhzh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.SFKXG
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String sfkxg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZHCZQDID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String zhczqdid;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZHCZRZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String zhczrzh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZHCZRXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String zhczrxm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZHCZRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date zhczrq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHLBDM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhlbdm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.SSYWWD
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String ssywwd;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHDLZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhdlzh1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHDLZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhdlzh2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHEMAIL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhemail;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.QQHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String qqhm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WXHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wxhm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WBHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wbhm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String zjhm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.MMYZFS
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String mmyzfs;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.SFYXXGMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String sfyxxgmm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WT1WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wt1wt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WT1DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wt1da;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.WT2DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String wt2da;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHUKEY
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhukey;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.SFYXDL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String sfyxdl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.ZHYXQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date zhyxq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHGH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhgh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhxm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHLXDH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhlxdh;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHSJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhsjhm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHSR
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date yhsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHGRAH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhgrah;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHZW
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhzw;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHJTDZ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhjtdz;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.BEIZHU
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String beizhu;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.SSBM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String ssbm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHZT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private String yhzt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHZCRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date yhzcrq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHTYRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date yhtyrq;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column PUBGJJ.FROPERACCNT.YHXHRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    private Date yhxhrq;

    private String yhsjssqy;
    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.FROAID
     * @return  the value of PUBGJJ.FROPERACCNT.FROAID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getFroaid() {
        return froaid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.FROAID
     * @param froaid  the value for PUBGJJ.FROPERACCNT.FROAID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setFroaid(String froaid) {
        this.froaid = froaid == null ? null : froaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.XGYHZH1
     * @return  the value of PUBGJJ.FROPERACCNT.XGYHZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getXgyhzh1() {
        return xgyhzh1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.XGYHZH1
     * @param xgyhzh1  the value for PUBGJJ.FROPERACCNT.XGYHZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setXgyhzh1(String xgyhzh1) {
        this.xgyhzh1 = xgyhzh1 == null ? null : xgyhzh1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.XGYHZH2
     * @return  the value of PUBGJJ.FROPERACCNT.XGYHZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getXgyhzh2() {
        return xgyhzh2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.XGYHZH2
     * @param xgyhzh2  the value for PUBGJJ.FROPERACCNT.XGYHZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setXgyhzh2(String xgyhzh2) {
        this.xgyhzh2 = xgyhzh2 == null ? null : xgyhzh2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZJLX
     * @return  the value of PUBGJJ.FROPERACCNT.ZJLX
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getZjlx() {
        return zjlx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZJLX
     * @param zjlx  the value for PUBGJJ.FROPERACCNT.ZJLX
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZjlx(String zjlx) {
        this.zjlx = zjlx == null ? null : zjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHDLMM
     * @return  the value of PUBGJJ.FROPERACCNT.YHDLMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhdlmm() {
        return yhdlmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHDLMM
     * @param yhdlmm  the value for PUBGJJ.FROPERACCNT.YHDLMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhdlmm(String yhdlmm) {
        this.yhdlmm = yhdlmm == null ? null : yhdlmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WT2WT
     * @return  the value of PUBGJJ.FROPERACCNT.WT2WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWt2wt() {
        return wt2wt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WT2WT
     * @param wt2wt  the value for PUBGJJ.FROPERACCNT.WT2WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWt2wt(String wt2wt) {
        this.wt2wt = wt2wt == null ? null : wt2wt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.FROANO
     * @return  the value of PUBGJJ.FROPERACCNT.FROANO
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getFroano() {
        return froano;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.FROANO
     * @param froano  the value for PUBGJJ.FROPERACCNT.FROANO
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setFroano(String froano) {
        this.froano = froano == null ? null : froano.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.AREALIMIT
     * @return  the value of PUBGJJ.FROPERACCNT.AREALIMIT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getArealimit() {
        return arealimit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.AREALIMIT
     * @param arealimit  the value for PUBGJJ.FROPERACCNT.AREALIMIT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setArealimit(String arealimit) {
        this.arealimit = arealimit == null ? null : arealimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.KCZYHZH
     * @return  the value of PUBGJJ.FROPERACCNT.KCZYHZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getKczyhzh() {
        return kczyhzh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.KCZYHZH
     * @param kczyhzh  the value for PUBGJJ.FROPERACCNT.KCZYHZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setKczyhzh(String kczyhzh) {
        this.kczyhzh = kczyhzh == null ? null : kczyhzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.SFKXG
     * @return  the value of PUBGJJ.FROPERACCNT.SFKXG
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getSfkxg() {
        return sfkxg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.SFKXG
     * @param sfkxg  the value for PUBGJJ.FROPERACCNT.SFKXG
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setSfkxg(String sfkxg) {
        this.sfkxg = sfkxg == null ? null : sfkxg.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZHCZQDID
     * @return  the value of PUBGJJ.FROPERACCNT.ZHCZQDID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getZhczqdid() {
        return zhczqdid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZHCZQDID
     * @param zhczqdid  the value for PUBGJJ.FROPERACCNT.ZHCZQDID
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZhczqdid(String zhczqdid) {
        this.zhczqdid = zhczqdid == null ? null : zhczqdid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZHCZRZH
     * @return  the value of PUBGJJ.FROPERACCNT.ZHCZRZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getZhczrzh() {
        return zhczrzh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZHCZRZH
     * @param zhczrzh  the value for PUBGJJ.FROPERACCNT.ZHCZRZH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZhczrzh(String zhczrzh) {
        this.zhczrzh = zhczrzh == null ? null : zhczrzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZHCZRXM
     * @return  the value of PUBGJJ.FROPERACCNT.ZHCZRXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getZhczrxm() {
        return zhczrxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZHCZRXM
     * @param zhczrxm  the value for PUBGJJ.FROPERACCNT.ZHCZRXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZhczrxm(String zhczrxm) {
        this.zhczrxm = zhczrxm == null ? null : zhczrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZHCZRQ
     * @return  the value of PUBGJJ.FROPERACCNT.ZHCZRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getZhczrq() {
        return zhczrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZHCZRQ
     * @param zhczrq  the value for PUBGJJ.FROPERACCNT.ZHCZRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZhczrq(Date zhczrq) {
        this.zhczrq = zhczrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHLBDM
     * @return  the value of PUBGJJ.FROPERACCNT.YHLBDM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhlbdm() {
        return yhlbdm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHLBDM
     * @param yhlbdm  the value for PUBGJJ.FROPERACCNT.YHLBDM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhlbdm(String yhlbdm) {
        this.yhlbdm = yhlbdm == null ? null : yhlbdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.SSYWWD
     * @return  the value of PUBGJJ.FROPERACCNT.SSYWWD
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getSsywwd() {
        return ssywwd;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.SSYWWD
     * @param ssywwd  the value for PUBGJJ.FROPERACCNT.SSYWWD
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setSsywwd(String ssywwd) {
        this.ssywwd = ssywwd == null ? null : ssywwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHDLZH1
     * @return  the value of PUBGJJ.FROPERACCNT.YHDLZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhdlzh1() {
        return yhdlzh1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHDLZH1
     * @param yhdlzh1  the value for PUBGJJ.FROPERACCNT.YHDLZH1
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhdlzh1(String yhdlzh1) {
        this.yhdlzh1 = yhdlzh1 == null ? null : yhdlzh1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHDLZH2
     * @return  the value of PUBGJJ.FROPERACCNT.YHDLZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhdlzh2() {
        return yhdlzh2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHDLZH2
     * @param yhdlzh2  the value for PUBGJJ.FROPERACCNT.YHDLZH2
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhdlzh2(String yhdlzh2) {
        this.yhdlzh2 = yhdlzh2 == null ? null : yhdlzh2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHEMAIL
     * @return  the value of PUBGJJ.FROPERACCNT.YHEMAIL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhemail() {
        return yhemail;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHEMAIL
     * @param yhemail  the value for PUBGJJ.FROPERACCNT.YHEMAIL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhemail(String yhemail) {
        this.yhemail = yhemail == null ? null : yhemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.QQHM
     * @return  the value of PUBGJJ.FROPERACCNT.QQHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getQqhm() {
        return qqhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.QQHM
     * @param qqhm  the value for PUBGJJ.FROPERACCNT.QQHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setQqhm(String qqhm) {
        this.qqhm = qqhm == null ? null : qqhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WXHM
     * @return  the value of PUBGJJ.FROPERACCNT.WXHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWxhm() {
        return wxhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WXHM
     * @param wxhm  the value for PUBGJJ.FROPERACCNT.WXHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWxhm(String wxhm) {
        this.wxhm = wxhm == null ? null : wxhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WBHM
     * @return  the value of PUBGJJ.FROPERACCNT.WBHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWbhm() {
        return wbhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WBHM
     * @param wbhm  the value for PUBGJJ.FROPERACCNT.WBHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWbhm(String wbhm) {
        this.wbhm = wbhm == null ? null : wbhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZJHM
     * @return  the value of PUBGJJ.FROPERACCNT.ZJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZJHM
     * @param zjhm  the value for PUBGJJ.FROPERACCNT.ZJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.MMYZFS
     * @return  the value of PUBGJJ.FROPERACCNT.MMYZFS
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getMmyzfs() {
        return mmyzfs;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.MMYZFS
     * @param mmyzfs  the value for PUBGJJ.FROPERACCNT.MMYZFS
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setMmyzfs(String mmyzfs) {
        this.mmyzfs = mmyzfs == null ? null : mmyzfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.SFYXXGMM
     * @return  the value of PUBGJJ.FROPERACCNT.SFYXXGMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getSfyxxgmm() {
        return sfyxxgmm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.SFYXXGMM
     * @param sfyxxgmm  the value for PUBGJJ.FROPERACCNT.SFYXXGMM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setSfyxxgmm(String sfyxxgmm) {
        this.sfyxxgmm = sfyxxgmm == null ? null : sfyxxgmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WT1WT
     * @return  the value of PUBGJJ.FROPERACCNT.WT1WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWt1wt() {
        return wt1wt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WT1WT
     * @param wt1wt  the value for PUBGJJ.FROPERACCNT.WT1WT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWt1wt(String wt1wt) {
        this.wt1wt = wt1wt == null ? null : wt1wt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WT1DA
     * @return  the value of PUBGJJ.FROPERACCNT.WT1DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWt1da() {
        return wt1da;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WT1DA
     * @param wt1da  the value for PUBGJJ.FROPERACCNT.WT1DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWt1da(String wt1da) {
        this.wt1da = wt1da == null ? null : wt1da.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.WT2DA
     * @return  the value of PUBGJJ.FROPERACCNT.WT2DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getWt2da() {
        return wt2da;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.WT2DA
     * @param wt2da  the value for PUBGJJ.FROPERACCNT.WT2DA
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setWt2da(String wt2da) {
        this.wt2da = wt2da == null ? null : wt2da.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHUKEY
     * @return  the value of PUBGJJ.FROPERACCNT.YHUKEY
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhukey() {
        return yhukey;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHUKEY
     * @param yhukey  the value for PUBGJJ.FROPERACCNT.YHUKEY
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhukey(String yhukey) {
        this.yhukey = yhukey == null ? null : yhukey.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.SFYXDL
     * @return  the value of PUBGJJ.FROPERACCNT.SFYXDL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getSfyxdl() {
        return sfyxdl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.SFYXDL
     * @param sfyxdl  the value for PUBGJJ.FROPERACCNT.SFYXDL
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setSfyxdl(String sfyxdl) {
        this.sfyxdl = sfyxdl == null ? null : sfyxdl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.ZHYXQ
     * @return  the value of PUBGJJ.FROPERACCNT.ZHYXQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getZhyxq() {
        return zhyxq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.ZHYXQ
     * @param zhyxq  the value for PUBGJJ.FROPERACCNT.ZHYXQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setZhyxq(Date zhyxq) {
        this.zhyxq = zhyxq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHGH
     * @return  the value of PUBGJJ.FROPERACCNT.YHGH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhgh() {
        return yhgh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHGH
     * @param yhgh  the value for PUBGJJ.FROPERACCNT.YHGH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhgh(String yhgh) {
        this.yhgh = yhgh == null ? null : yhgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHXM
     * @return  the value of PUBGJJ.FROPERACCNT.YHXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhxm() {
        return yhxm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHXM
     * @param yhxm  the value for PUBGJJ.FROPERACCNT.YHXM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhxm(String yhxm) {
        this.yhxm = yhxm == null ? null : yhxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHLXDH
     * @return  the value of PUBGJJ.FROPERACCNT.YHLXDH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhlxdh() {
        return yhlxdh;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHLXDH
     * @param yhlxdh  the value for PUBGJJ.FROPERACCNT.YHLXDH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhlxdh(String yhlxdh) {
        this.yhlxdh = yhlxdh == null ? null : yhlxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHSJHM
     * @return  the value of PUBGJJ.FROPERACCNT.YHSJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhsjhm() {
        return yhsjhm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHSJHM
     * @param yhsjhm  the value for PUBGJJ.FROPERACCNT.YHSJHM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhsjhm(String yhsjhm) {
        this.yhsjhm = yhsjhm == null ? null : yhsjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHSR
     * @return  the value of PUBGJJ.FROPERACCNT.YHSR
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getYhsr() {
        return yhsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHSR
     * @param yhsr  the value for PUBGJJ.FROPERACCNT.YHSR
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhsr(Date yhsr) {
        this.yhsr = yhsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHGRAH
     * @return  the value of PUBGJJ.FROPERACCNT.YHGRAH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhgrah() {
        return yhgrah;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHGRAH
     * @param yhgrah  the value for PUBGJJ.FROPERACCNT.YHGRAH
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhgrah(String yhgrah) {
        this.yhgrah = yhgrah == null ? null : yhgrah.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHZW
     * @return  the value of PUBGJJ.FROPERACCNT.YHZW
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhzw() {
        return yhzw;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHZW
     * @param yhzw  the value for PUBGJJ.FROPERACCNT.YHZW
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhzw(String yhzw) {
        this.yhzw = yhzw == null ? null : yhzw.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHJTDZ
     * @return  the value of PUBGJJ.FROPERACCNT.YHJTDZ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhjtdz() {
        return yhjtdz;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHJTDZ
     * @param yhjtdz  the value for PUBGJJ.FROPERACCNT.YHJTDZ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhjtdz(String yhjtdz) {
        this.yhjtdz = yhjtdz == null ? null : yhjtdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.BEIZHU
     * @return  the value of PUBGJJ.FROPERACCNT.BEIZHU
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getBeizhu() {
        return beizhu;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.BEIZHU
     * @param beizhu  the value for PUBGJJ.FROPERACCNT.BEIZHU
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setBeizhu(String beizhu) {
        this.beizhu = beizhu == null ? null : beizhu.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.SSBM
     * @return  the value of PUBGJJ.FROPERACCNT.SSBM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getSsbm() {
        return ssbm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.SSBM
     * @param ssbm  the value for PUBGJJ.FROPERACCNT.SSBM
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setSsbm(String ssbm) {
        this.ssbm = ssbm == null ? null : ssbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHZT
     * @return  the value of PUBGJJ.FROPERACCNT.YHZT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public String getYhzt() {
        return yhzt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHZT
     * @param yhzt  the value for PUBGJJ.FROPERACCNT.YHZT
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhzt(String yhzt) {
        this.yhzt = yhzt == null ? null : yhzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHZCRQ
     * @return  the value of PUBGJJ.FROPERACCNT.YHZCRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getYhzcrq() {
        return yhzcrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHZCRQ
     * @param yhzcrq  the value for PUBGJJ.FROPERACCNT.YHZCRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhzcrq(Date yhzcrq) {
        this.yhzcrq = yhzcrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHTYRQ
     * @return  the value of PUBGJJ.FROPERACCNT.YHTYRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getYhtyrq() {
        return yhtyrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHTYRQ
     * @param yhtyrq  the value for PUBGJJ.FROPERACCNT.YHTYRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhtyrq(Date yhtyrq) {
        this.yhtyrq = yhtyrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column PUBGJJ.FROPERACCNT.YHXHRQ
     * @return  the value of PUBGJJ.FROPERACCNT.YHXHRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public Date getYhxhrq() {
        return yhxhrq;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column PUBGJJ.FROPERACCNT.YHXHRQ
     * @param yhxhrq  the value for PUBGJJ.FROPERACCNT.YHXHRQ
     * @mbggenerated  Thu May 24 08:21:35 CST 2018
     */
    public void setYhxhrq(Date yhxhrq) {
        this.yhxhrq = yhxhrq;
    }

    public String getYhsjssqy() {
        return yhsjssqy;
    }

    public void setYhsjssqy(String yhsjssqy) {
        this.yhsjssqy = yhsjssqy;
    }
}